import org.example.Board
import org.example.CellState
import org.example.Game
import org.example.Player
import org.example.validations.*
import kotlin.test.Test
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class Test {

    private val board = Board(7,6)
    private val player1 = Player("Player1", CellState.X, board)
    private val player2 = Player("Player2", CellState.O, board)
    private val game = Game(board, player1, player2)


    @Test
    fun testBelowCellsValidation() {
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(1))
        assertTrue(game.checkWin(1))

        assertTrue(BelowCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(AboveCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(1, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(1, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(1, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(1, board, CellState.O))
    }

    @Test
    fun testLeftCellsValidation() {
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertTrue(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }

    @Test
    fun testRightCellsValidation() {
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertTrue(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }

    @Test
    fun testLowerLeftCellsValidation() {
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertTrue(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }

    @Test
    fun testLowerRightCellsValidation() {
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertFalse(game.checkWin(4))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertTrue(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }

    @Test
    fun testUpperLeftCellsValidation() {
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(1))
        assertFalse(game.checkWin(1))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(2))
        assertFalse(game.checkWin(2))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertTrue(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }

    @Test
    fun testUpperRightCellsValidation() {
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(7))
        assertFalse(game.checkWin(7))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(6))
        assertFalse(game.checkWin(6))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(5))
        assertFalse(game.checkWin(5))
        assertTrue(game.isCurrentMoveValid(3))
        assertFalse(game.checkWin(3))
        assertTrue(game.isCurrentMoveValid(4))
        assertTrue(game.checkWin(4))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.X))
        assertFalse(UpperRightCellsValidation().isWinningMove(4, board, CellState.X))

        assertFalse(BelowCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(AboveCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(RightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(LowerRightCellsValidation().isWinningMove(4, board, CellState.O))
        assertFalse(UpperLeftCellsValidation().isWinningMove(4, board, CellState.O))
        assertTrue(UpperRightCellsValidation().isWinningMove(4, board, CellState.O))
    }
}